# Generated by Django 4.2.8 on 2024-07-02 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commentdislike_commentdisliketemp_commentlike_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentliketemp',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentliketemp',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentliketemp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislikes_temp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes_temp',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_comments', through='blog.CommentDislike', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', through='blog.CommentLike', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.DeleteModel(
            name='CommentDislikeTemp',
        ),
        migrations.DeleteModel(
            name='CommentLikeTemp',
        ),
    ]
