# Generated by Django 4.2.8 on 2024-07-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва тегу')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='draft',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='draft',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='draft',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drafts/photos/'),
        ),
        migrations.AddField(
            model_name='draft',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опублікована')], default='draft', max_length=10),
        ),
    ]
