# Generated by Django 4.2.8 on 2024-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_announcement_options_announcement_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', verbose_name='Відео'),
        ),
    ]
